# Generated manually for AA FleetOps 0.1.0a1
import decimal
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="CommsPreset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("channel_name", models.CharField(blank=True, max_length=255)),
                ("voice_url", models.CharField(blank=True, help_text="Supports mumble://, https:// and other voice links.", max_length=500)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="DiscordWebhook",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("webhook_url", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="FleetOpsSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("attendance_limit", models.PositiveIntegerField(blank=True, help_text="Maximum attendance credits per Alliance Auth user per fleet. Empty = unlimited.", null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ("tracking_interval", models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(30)])),
                ("stale_threshold", models.PositiveIntegerField(default=180, validators=[django.core.validators.MinValueValidator(60)])),
                ("auto_end_enabled", models.BooleanField(default=True)),
                ("auto_end_missing_count", models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(2)])),
                ("incentive_enabled", models.BooleanField(default=False)),
                ("incentive_minimum_fleets", models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ("data_retention_days", models.PositiveIntegerField(default=365)),
            ],
            options={
                "verbose_name": "FleetOps setting",
                "verbose_name_plural": "FleetOps settings",
                "permissions": [
                    ("basic_access", "Can access FleetOps"), ("start_fleet", "Can start fleets"),
                    ("manage_own_fleet", "Can manage own fleets"), ("manage_fleets", "Can manage all fleets"),
                    ("view_corp_stats", "Can view own corporation statistics"), ("view_all_stats", "Can view all FleetOps statistics"),
                    ("manage_attendance", "Can manage attendance"), ("manage_incentives", "Can manage FC incentives"),
                    ("manage_configuration", "Can manage FleetOps configuration"), ("view_audit_log", "Can view FleetOps audit log"),
                ],
            },
        ),
        migrations.CreateModel(
            name="FleetType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("short_name", models.CharField(blank=True, max_length=30)),
                ("point_weight", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=8)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={"ordering": ["sort_order", "name"]},
        ),
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("template_type", models.CharField(choices=[("ping", "Ping"), ("motd", "MOTD")], max_length=20)),
                ("content", models.TextField()),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"ordering": ["template_type", "name"]},
        ),
        migrations.CreateModel(
            name="ChannelPreset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("channel_type", models.CharField(choices=[("logi", "Logi"), ("boost", "Boost")], max_length=20)),
                ("channel_value", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"ordering": ["channel_type", "name"]},
        ),
        migrations.CreateModel(
            name="PingTarget",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("target_value", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("webhook", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="fleetops.discordwebhook")),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="FleetOperation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("start_request_id", models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("starting", "Starting"), ("active", "Active"), ("ending", "Ending"), ("closed", "Closed"), ("cancelled", "Cancelled"), ("error", "Error")], db_index=True, default="draft", max_length=20)),
                ("fc_character_id", models.BigIntegerField(db_index=True)),
                ("fc_character_name", models.CharField(max_length=255)),
                ("fc_main_character_id", models.BigIntegerField(blank=True, db_index=True, null=True)),
                ("fc_main_character_name", models.CharField(blank=True, max_length=255)),
                ("fleet_boss_character_id", models.BigIntegerField(blank=True, null=True)),
                ("esi_fleet_id", models.BigIntegerField(blank=True, db_index=True, null=True)),
                ("fleet_point_weight_snapshot", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=8)),
                ("doctrine_name", models.CharField(blank=True, max_length=255)),
                ("doctrine_external_id", models.CharField(blank=True, max_length=255)),
                ("doctrine_source", models.CharField(blank=True, max_length=50)),
                ("formup", models.CharField(max_length=255)),
                ("additional_message", models.TextField(blank=True)),
                ("ping_text", models.TextField(blank=True)),
                ("motd_text", models.TextField(blank=True)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("last_esi_update", models.DateTimeField(blank=True, null=True)),
                ("tracking_enabled", models.BooleanField(default=False)),
                ("fleet_missing_count", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("boost_channel", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="fleetops_boost_operations", to="fleetops.channelpreset")),
                ("comms", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="fleetops.commspreset")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="fleetops_created_operations", to=settings.AUTH_USER_MODEL)),
                ("fc_user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="fleetops_fc_operations", to=settings.AUTH_USER_MODEL)),
                ("fleet_type", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="fleetops.fleettype")),
                ("logi_channel", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="fleetops_logi_operations", to="fleetops.channelpreset")),
                ("motd_template", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="fleetops_motd_operations", to="fleetops.messagetemplate")),
                ("ping_target", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="fleetops.pingtarget")),
                ("ping_template", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="fleetops_ping_operations", to="fleetops.messagetemplate")),
            ],
            options={"ordering": ["-started_at", "-created_at"]},
        ),
        migrations.CreateModel(
            name="IncentivePeriod",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ("status", models.CharField(choices=[("open", "Open"), ("review", "Review"), ("finalized", "Finalized")], default="open", max_length=20)),
                ("budget", models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ("minimum_fleets", models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ("policy_snapshot", models.JSONField(blank=True, default=dict)),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                ("finalized_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="fleetops_finalized_periods", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-year", "-month"]},
        ),
        migrations.CreateModel(
            name="OperationAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(max_length=50)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("success", "Success"), ("failed", "Failed")], default="pending", max_length=20)),
                ("error_message", models.TextField(blank=True)),
                ("attempts", models.PositiveIntegerField(default=1)),
                ("executed_at", models.DateTimeField(auto_now=True)),
                ("operation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="actions", to="fleetops.fleetoperation")),
            ],
            options={"ordering": ["executed_at"]},
        ),
        migrations.CreateModel(
            name="FleetMemberState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("character_id", models.BigIntegerField()),
                ("character_name", models.CharField(max_length=255)),
                ("main_character_id", models.BigIntegerField(blank=True, db_index=True, null=True)),
                ("main_character_name", models.CharField(blank=True, max_length=255)),
                ("corporation_id", models.BigIntegerField(blank=True, db_index=True, null=True)),
                ("corporation_name", models.CharField(blank=True, max_length=255)),
                ("alliance_id", models.BigIntegerField(blank=True, null=True)),
                ("alliance_name", models.CharField(blank=True, max_length=255)),
                ("ship_type_id", models.BigIntegerField(blank=True, null=True)),
                ("ship_type_name", models.CharField(blank=True, max_length=255)),
                ("solar_system_id", models.BigIntegerField(blank=True, db_index=True, null=True)),
                ("solar_system_name", models.CharField(blank=True, max_length=255)),
                ("fleet_role", models.CharField(blank=True, max_length=50)),
                ("wing_id", models.BigIntegerField(blank=True, null=True)),
                ("squad_id", models.BigIntegerField(blank=True, null=True)),
                ("first_seen", models.DateTimeField()), ("last_seen", models.DateTimeField()),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("auth_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="fleetops_member_states", to=settings.AUTH_USER_MODEL)),
                ("operation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="member_states", to="fleetops.fleetoperation")),
            ],
            options={"ordering": ["character_name"]},
        ),
        migrations.CreateModel(
            name="FleetMemberEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("character_id", models.BigIntegerField(db_index=True)),
                ("character_name", models.CharField(max_length=255)),
                ("event_type", models.CharField(choices=[("join", "Join"), ("leave", "Leave"), ("rejoin", "Rejoin"), ("ship_change", "Ship change"), ("system_change", "System change"), ("role_change", "Role change"), ("wing_change", "Wing change"), ("squad_change", "Squad change")], db_index=True, max_length=30)),
                ("old_value", models.CharField(blank=True, max_length=255)), ("new_value", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("operation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="member_events", to="fleetops.fleetoperation")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("character_id", models.BigIntegerField()), ("character_name", models.CharField(max_length=255)),
                ("main_character_id", models.BigIntegerField(blank=True, db_index=True, null=True)), ("main_character_name", models.CharField(blank=True, max_length=255)),
                ("corporation_id", models.BigIntegerField(blank=True, db_index=True, help_text="Main character corporation at attendance time.", null=True)), ("corporation_name", models.CharField(blank=True, max_length=255)),
                ("source", models.CharField(choices=[("automatic", "Automatic"), ("manual", "Manual"), ("imported", "Imported")], max_length=20)),
                ("attendance_value", models.PositiveIntegerField(default=1)), ("granted", models.BooleanField(db_index=True, default=True)), ("capped", models.BooleanField(default=False)),
                ("first_seen", models.DateTimeField(blank=True, null=True)), ("last_seen", models.DateTimeField(blank=True, null=True)), ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
                ("auth_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="fleetops_attendance", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="fleetops_attendance_created", to=settings.AUTH_USER_MODEL)),
                ("operation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attendance_records", to="fleetops.fleetoperation")),
            ],
            options={"ordering": ["character_name"]},
        ),
        migrations.CreateModel(
            name="MonthlyFCStatistic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fleet_count", models.PositiveIntegerField(default=0)),
                ("total_points", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=12)),
                ("fleet_type_breakdown", models.JSONField(blank=True, default=dict)),
                ("eligible", models.BooleanField(default=False)), ("waived", models.BooleanField(default=False)),
                ("calculated_payout", models.BigIntegerField(default=0)), ("final_payout", models.BigIntegerField(default=0)),
                ("fc_user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="fleetops_monthly_fc_stats", to=settings.AUTH_USER_MODEL)),
                ("period", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="fc_statistics", to="fleetops.incentiveperiod")),
            ],
            options={"ordering": ["-total_points", "fc_user__username"]},
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(db_index=True, max_length=100)), ("object_type", models.CharField(max_length=100)), ("object_id", models.CharField(max_length=100)),
                ("old_value", models.JSONField(blank=True, null=True)), ("new_value", models.JSONField(blank=True, null=True)), ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="fleetops_audit_entries", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddConstraint(model_name="channelpreset", constraint=models.UniqueConstraint(fields=("channel_type", "name"), name="fleetops_unique_channel_preset")),
        migrations.AddConstraint(model_name="messagetemplate", constraint=models.UniqueConstraint(fields=("template_type", "name"), name="fleetops_unique_message_template")),
        migrations.AddConstraint(model_name="operationaction", constraint=models.UniqueConstraint(fields=("operation", "action"), name="fleetops_unique_operation_action")),
        migrations.AddConstraint(model_name="fleetmemberstate", constraint=models.UniqueConstraint(fields=("operation", "character_id"), name="fleetops_unique_operation_character_state")),
        migrations.AddConstraint(model_name="attendancerecord", constraint=models.UniqueConstraint(fields=("operation", "character_id", "source"), name="fleetops_unique_attendance_source")),
        migrations.AddConstraint(model_name="incentiveperiod", constraint=models.UniqueConstraint(fields=("year", "month"), name="fleetops_unique_incentive_period")),
        migrations.AddConstraint(model_name="monthlyfcstatistic", constraint=models.UniqueConstraint(fields=("period", "fc_user"), name="fleetops_unique_monthly_fc_stat")),
        migrations.AddIndex(model_name="fleetoperation", index=models.Index(fields=["status", "tracking_enabled"], name="fleetops_fl_status_8c6d24_idx")),
    ]
