# Generated by Django 5.2.17 on 2026-10-06 07:43

import django.core.validators
import fleetops.models
from decimal import Decimal
from django.db import migrations, models


def keep_one_default_template(apps, schema_editor):
    # Keep the default that was already in use (first active one by name) and clear the others.
    MessageTemplate = apps.get_model("fleetops", "MessageTemplate")
    defaults = MessageTemplate.objects.filter(is_default=True)
    for template_type in set(defaults.values_list("template_type", flat=True)):
        same_type = defaults.filter(template_type=template_type).order_by("-is_active", "name", "pk")
        same_type.exclude(pk=same_type.first().pk).update(is_default=False)


class Migration(migrations.Migration):

    dependencies = [
        ("fleetops", "0004_attendance_modes_permissions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendancerecord",
            options={"ordering": ["character_name", "created_at"]},
        ),
        migrations.AlterField(
            model_name="discordwebhook",
            name="webhook_url",
            field=models.TextField(
                validators=[fleetops.models.validate_discord_webhook_url]
            ),
        ),
        migrations.AlterField(
            model_name="fleetopssettings",
            name="data_retention_days",
            field=models.PositiveIntegerField(
                default=365,
                help_text="Attendance/event history retention in days. Minimum 365 days, maximum 36500 days (100 years).",
                validators=[
                    django.core.validators.MinValueValidator(365),
                    django.core.validators.MaxValueValidator(36500),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="fleetopssettings",
            name="history_alliance_ids",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated alliance IDs whose current members may appear in attendance history. Empty disables membership pruning.",
                max_length=500,
                validators=[fleetops.models.validate_alliance_ids],
            ),
        ),
        migrations.AlterField(
            model_name="fleettype",
            name="point_weight",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="incentiveperiod",
            name="year",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(2003),
                    django.core.validators.MaxValueValidator(2200),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="messagetemplate",
            name="content",
            field=models.TextField(
                validators=[fleetops.models.validate_template_syntax]
            ),
        ),
        migrations.RunPython(keep_one_default_template, migrations.RunPython.noop),
    ]
